### ISSUE TITLE
java.lang.ClassNotFoundException: clj_facebook_graph.FacebookGraphException (error_handling.clj:9)

### ISSUE THREAD

**Issue by adinapoli** [maxweber/clj-facebook-graph#1]
Hi max,
in first place I'm very happy you have decided to start this project, I think it will be very useful.
Just a mental note: I haven't found a simple and permanent fix for the typo:

java.lang.ClassNotFoundException: clj_facebook_graph.FacebookGraphException (error_handling.clj:9)

This is normally fixed with lein compile, but not in this case (Am I missing some steps?)
I had to manually compile the Exception from the repl and put it into my project's classes directory.

One solution can be to create a java class for the Exception, so that lein compile can work directly from the command line.

Cheers,
Alfredo

**Comment by maxweber** [comment]
Hi Alfredo,
I have fixed the issue with the java.lang.ClassNotFoundException: clj_facebook_graph.FacebookGraphException by adding the class to the :aot section of the project.clj. Now the "normal fix" to invoke "lein compile" will work.
At the moment the clj-facebook-graph project is rather a good starting point to do your own Clojure Facebook Graph integration than a full-blown Clojure library for the Facebook Graph. I'm going to use clj-facebook-graph for my startup, but at the moment the project is not used in production anywhere. So for example I would guess that the handling of where to keep the Facebook authentication data in the session is less than optimal at the moment. However with Ring and clj-http I would say that clj-facebook-graph has a rock-solid foundation. I would be very happy, if you contribute your clj-facebook-graph enhancement back to the project. I'm also going to make a Blog-Post about clj-facebook-graph public in the next days on my new Blog: http://max-weber.tumblr.com/

Best regards

Max

**Comment by adinapoli** [comment]
I'm using your library for an university project, so I'll be happy to signal and try to fix bugs if they will show up. Good luck for your startup, I'll keep an eye on your blog :)
Bye,
Alfredo

ps. Now that lein compile is fixed, I will push clj-facebook on Clojars :)
